"""
Streamlit UI for the Reply-Intent Classifier (Grok-powered backend).

Two tabs:
1. Classify — paste a creator reply, get predicted intent + confidence (live LLM call)
2. Test Results — view the held-out test set predictions vs actual labels
   (from results/test_predictions.json, generated by evaluate.py)

Run:
    streamlit run app.py
"""

import os
import json
import streamlit as st
from dotenv import load_dotenv
from classifier import classify_reply, LABELS

load_dotenv()

st.set_page_config(page_title="Reply-Intent Classifier", page_icon="\U0001F50D", layout="centered")

INTENT_COLORS = {
    "interested": "#22c55e",
    "not_interested": "#ef4444",
    "pricing_query": "#3b82f6",
    "availability_query": "#eab308",
    "unclear": "#6b7280",
}


def render_badge(intent: str):
    color = INTENT_COLORS.get(intent, "#6b7280")
    st.markdown(
        f"""
        <span style="
            background-color:{color};
            color:white;
            padding:6px 14px;
            border-radius:999px;
            font-weight:600;
            font-size:14px;
        ">{intent}</span>
        """,
        unsafe_allow_html=True,
    )


with st.sidebar:
    st.header("Setup")
    key_present = bool(os.environ.get("XAI_API_KEY"))
    if key_present:
        st.success("XAI_API_KEY detected")
    else:
        st.error("XAI_API_KEY not set")
        st.caption("This app calls Grok via the xAI API. Set the key before classifying:")
        st.code("export XAI_API_KEY=your-key-here", language="bash")
        st.caption("Or add it to a .env file in the project root.")
    st.divider()
    st.caption("Classifier: Grok few-shot prompt (see classifier.py)")
    st.caption("Categories:")
    for label in LABELS:
        st.caption(f"\u2022 {label}")


st.title("\U0001F50D Reply-Intent Classifier")
st.caption("Classify a creator's DM/email reply into an outreach intent category — powered by Grok via an LLM prompt, not a locally trained model.")

tab1, tab2 = st.tabs(["Classify a Message", "Test Set Results"])

with tab1:
    message = st.text_area(
        "Paste a creator reply",
        placeholder='e.g. "What\'s your rate for a story post?"',
        height=120,
    )

    if st.button("Classify", type="primary", disabled=not key_present):
        if not message.strip():
            st.warning("Please enter a message first.")
        else:
            with st.spinner("Calling Grok..."):
                try:
                    result = classify_reply(message)
                    st.write("")
                    render_badge(result["intent"])
                    st.metric("Confidence", f"{result['confidence']:.0%}")
                except Exception as e:
                    st.error(f"Classification failed: {e}")

with tab2:
    results_path = "results/test_predictions.json"
    if not os.path.exists(results_path):
        st.info(
            "No results file found yet. Run `python evaluate.py` first to generate "
            f"`{results_path}`, then reload this page."
        )
    else:
        with open(results_path) as f:
            data = json.load(f)

        st.metric("Test Set Accuracy", f"{data['accuracy']:.0%}", f"{data['correct']}/{data['total']} correct")
        st.divider()
        for row in data["predictions"]:
            cols = st.columns([5, 2, 2, 1])
            cols[0].write(row["text"])
            cols[1].write(f"actual: **{row['actual']}**")
            cols[2].write(f"pred: **{row['predicted']}**")
            cols[3].write("\u2705" if row["correct"] else "\u274C")